import express from 'express';
import authRouter from './auth.router';
import oauthRouter from './oauth.router';
import userRouter from './user.router';
import videoRouter from './video.router';
import chatRouter from './chat.router';
import searchRouter from './serach.router';
import sliderRouter from './slider.router';
import musicRouter from './music.router';
import crownRouter from './crown.router';
import walletRouter from './wallet.router';
import transferRouter from './transfer.router';
import transactionRouter from './transaction.router';
import videoReportRouter from './video.report.router';
import commentRouter from './comment.router';
import privacyRouter from './privacy.router';
import favoriteRouter from './favorite.router';
import notificationRouter from './notification.route';
import trendingRouter from './trending.router';
import editorRouter from './editor.router';
import testRouter from './test.router';
import verificationRouter from './verification.router';
import algorithmRouter from './algorithm.router';
import orderRouter from './order.router';
import videoForGuestRouter from './videoForGuest.router';
import searchForGuestRouter from './searchForGuest.router';
import userForGuestRoute from './userForGuest.router';
import musicForGuestRoute from './musicForGuest.router';
import languageRouter from './language.router';
const router = express();
router.use('/auth', authRouter);
router.use('/oauth', oauthRouter);
router.use('/user', userRouter);
router.use('/chat', chatRouter);
router.use('/comment', commentRouter);
router.use('/search', searchRouter);
router.use('/slider', sliderRouter);
router.use('/music', musicRouter);
router.use('/crown', crownRouter);
router.use('/wallet', walletRouter);
router.use('/transfer', transferRouter);
router.use('/transaction', transactionRouter);
router.use('/video/report', videoReportRouter);
router.use('/video', videoRouter);
router.use('/privacy', privacyRouter);
router.use('/favorite', favoriteRouter);
router.use('/notification', notificationRouter);
router.use('/trending', trendingRouter);
router.use('/editor', editorRouter);
router.use('/test', testRouter);
router.use('/verification', verificationRouter);
router.use('/algorithm', algorithmRouter);
router.use('/order', orderRouter);
router.use('/language', languageRouter);
router.use('/video-for-guest', videoForGuestRouter);
router.use('/search-for-guest', searchForGuestRouter);
router.use('/user-for-guest', userForGuestRoute);
router.use('/music-for-guest', musicForGuestRoute);
export default router;
